#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset
trap 'echo "$0: line $LINENO: exit status of last command: $?" >&2' ERR

this_dir=$(cd -P "$(dirname "$0")" && pwd)
cd "$this_dir"

docker build -t react-container-thing .
docker run react-container-thing
